server:
  port: 8080

spring:
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: ${DB_URL}?prepareThreshold=0&preparedStatementCacheQueries=0
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    

      
